pipeline:
  identifier: Build_NodejsPipe_1717102268776
  name: Build NodejsPipe
  orgIdentifier: default
  projectIdentifier: NodeJS_Pipeline
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.gitglobal
        repoName: NodejsPipe
  stages:
    - stage:
        name: Build Node App
        identifier: Build_Node_App
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: npm test
                  identifier: npm_test
                  spec:
                    shell: Sh
                    command: |-
                      npm install
                      npm run build --if-present
                      npm test
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.harnessImage
                    repo: alexjaballah/nodejs
                    tags:
                      - <+pipeline.sequenceId>
