pipeline:
  identifier: Build_NodejsPipe_1717102268776
  name: Build NodejsPipe
  orgIdentifier: default
  projectIdentifier: NodeJS_Pipeline
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.gitglobal
        repoName: NodejsPipe
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
