pipeline:
  identifier: Build_NodejsPipe_1717102268776
  name: Build NodejsPipe
  orgIdentifier: default
  projectIdentifier: NodeJS_Pipeline
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.gitglobal
        repoName: NodejsPipe
  stages:
    - stage:
        name: Build Node App
        identifier: Build_Node_App
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Install Node
                  identifier: installnode
                  spec:
                    shell: Sh
                    envVariables:
                      NODE_VERSION: 18.16.0
                    command: |-
                      mkdir $HOME/nodejs
                      curl -L https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64.tar.xz | tar xJ -C $HOME/nodejs
                      export PATH=$HOME/nodejs/node-v${NODE_VERSION}-linux-x64/bin:$PATH
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.harnessImage
                    repo: alexjaballah/nodejs
                    tags:
                      - <+pipeline.sequenceId>
